builds:
- env:
  - GODEBUG=cgocheck=0
  main: main.go
  binary: d8
  goos:
  - linux
  - darwin
  # - windows
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: linux
    goarch: arm64
checksum:
  name_template: "checksums.txt"
